from pathlib import Path

from datasets import load_dataset


# These are the DPO files generated by prepare_data.py.
TRAIN_FILE = r"D:\ticket-priority-bot\data\dpo\train.jsonl"
VALIDATION_FILE = r"D:\ticket-priority-bot\data\dpo\validation.jsonl"


print("=" * 60)
print("TESTING DPO DATASET LOADING")
print("=" * 60)


# Make sure the files exist before trying to load them.
print("\n[1/3] Checking files...")

for name, path in [
    ("DPO training dataset", TRAIN_FILE),
    ("DPO validation dataset", VALIDATION_FILE),
]:
    if Path(path).exists():
        print(f"  [OK] {name}: {path}")
    else:
        print(f"  [ERROR] {name} not found: {path}")
        raise FileNotFoundError(path)


# Load the training dataset separately.
print("\n[2/3] Loading DPO training dataset...")

try:
    train_dataset = load_dataset(
        "json",
        data_files=TRAIN_FILE,
        split="train",
    )

    print("  [OK] Training dataset loaded")
    print(f"  Number of examples: {len(train_dataset)}")
    print(f"  Columns: {train_dataset.column_names}")

except Exception as e:
    print("  [ERROR] Failed to load training dataset")
    print(f"  Error type: {type(e).__name__}")
    print(f"  Error: {e}")
    raise


# Load the validation dataset separately.
print("\n[3/3] Loading DPO validation dataset...")

try:
    validation_dataset = load_dataset(
        "json",
        data_files=VALIDATION_FILE,
        split="train",
    )

    print("  [OK] Validation dataset loaded")
    print(f"  Number of examples: {len(validation_dataset)}")
    print(f"  Columns: {validation_dataset.column_names}")

except Exception as e:
    print("  [ERROR] Failed to load validation dataset")
    print(f"  Error type: {type(e).__name__}")
    print(f"  Error: {e}")
    raise


# Show one example so we can verify the DPO format.
print("\n" + "=" * 60)
print("SAMPLE DPO EXAMPLE")
print("=" * 60)

print(train_dataset[0])


print("\n" + "=" * 60)
print("DPO DATASET TEST PASSED")
print("=" * 60)